language: go
go:
- 1.10.x
deploy:
  provider: releases
  api_key:
    secure: VxdV1s2jFlh8XnWw3B1j4LukzFvgaHdPmCIenKGx8UwYHVIsID7b67staXq0vBFVDM11YnN8QMfaB5gh922fyhei4mqzgEhyna5P5K6L25Nnq+4oYd3tw4JmR6uOvwd6dCddt0sxbXW2XHjhhAOcDZDMl7zXkt+ea8NeygQt6GagmHKCZWSi/i4JR3Gpt+sdLEyhqvWLj1Bz61OcUo7z/BRSDVxcOUIW5NCdJZUSMXYTXzsMZMuLE9E3/6xtOEqUy/4xau5F1843DYAJ2lBPWJxnvNyBgvdcYTByobawXbaBV2g2g9mhaw6lKmgzBP9pR9PPSCclUphykN1lbNgnPowA7bY78+vaIXxb1yOxCSsE9T0tbk803GjqUwhGcUMRJtTrARda1kBigzNItMS4mTkjhV/IogxrzFKU7qOg2xBbsb7JaF1RorP3ON2v5y1fTrauhkCMOFzrjE27gIqmHzPkGDleI82nf7JawkBNgz44yOkGtbdyveebtLWh7pPALSq5X4UbridpjAcpPzR15g+Sf4aRze7MY9NU2DrV+VdLeclkpe/UtFTIAcGfZHPSiuLM4YkVlpaF43gCrk6iBS5zdTylmeqD2V0dZG/iSqjQ7t53+nrCzZPLlYNViwoLJ+ZCqSEgQI3D6knHJPPr/+shvTkL2LDYVx3vLIM/ltQ=
  file: plugin-png.so
  skip_cleanup: true
  on:
    tags: true
